#!/bin/sh

[ -z "$FTP_USER" ] && FTP_USER=admin
[ -z "$FTP_PASSWORD" ] && FTP_PASSWORD=admin

adduser -D "$FTP_USER"
echo "$FTP_USER:$FTP_PASSWORD" | chpasswd
echo "user:password = $FTP_USER:$FTP_PASSWORD"

/usr/sbin/pure-ftpd -Y 2 -p 15477:15477 -P "192.168.99.100"

# -p = range port
# -P = public host stored in PUBLICHOST env var
# manual chpasswd =  Reads a file of login name and password pairs, and updates the passwords.
# pure-ftpd executable full explanation : https://wiki.debian-fr.xyz/Installation_de_Pure-FTP_avec_SSL_et_MySQL
# Tous les password et user sont visibles dans /etc/passwd
# adduser -D = without password

# Pour le SSL :  https://github.com/stilliard/docker-pure-ftpd#tls
